apiVersion: blaxel.ai/v1alpha1
kind: IntegrationConnection
metadata:
  name: context7-integration
spec:
  integration: context7
---
apiVersion: blaxel.ai/v1alpha1
kind: Function
metadata:
  displayName: context7
  name: context7
spec:
  integrationConnections:
    - context7-integration
  runtime:
    type: mcp
