apiVersion: blaxel.ai/v1alpha1
kind: IntegrationConnection
metadata:
  name: openai-integration
spec:
  integration: openai
  secret:
    apiKey: $OPENAI_API_KEY
---
apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  name: gpt-4o-mini
  displayName: gpt-4o-mini
spec:
  enabled: true
  runtime:
    model: gpt-4o-mini
    type: openai
  integrationConnections:
    - openai-integration
